# Generated by Django 5.1 on 2024-08-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_engine", "0002_mentorship_timeline"),
    ]

    operations = [
        migrations.AddField(
            model_name="timeline",
            name="privacy",
            field=models.CharField(
                choices=[("fin", "Finance"), ("edu", "Education")],
                default="public",
                max_length=10,
            ),
            preserve_default=False,
        ),
    ]
