# Generated by Django 5.1 on 2024-08-26 04:44

import django.db.models.deletion
import django.utils.timezone
import task_engine.custom_model_validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_engine", "0003_timeline_privacy"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="author",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tags",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tag",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="tag",
            name="title",
            field=models.CharField(
                max_length=50,
                validators=[task_engine.custom_model_validators.no_spaces_validator],
            ),
        ),
        migrations.AlterField(
            model_name="timeline",
            name="privacy",
            field=models.CharField(
                choices=[
                    ("own", "Owner Only"),
                    ("mnt_own", "Mentor Owner"),
                    ("pub", "Public"),
                ],
                max_length=10,
            ),
        ),
    ]
