# Generated by Django 5.0.7 on 2024-07-24 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_mentee', models.BooleanField(default=True)),
                ('is_mentor', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=5)),
                ('gender', models.CharField(max_length=10)),
                ('birth_year', models.IntegerField()),
                ('birth_month', models.IntegerField()),
                ('birth_date', models.IntegerField()),
                ('country_origin', models.CharField(max_length=30)),
                ('country_live', models.CharField(max_length=30, null=True)),
                ('age', models.IntegerField()),
                ('profile_photo', models.CharField(max_length=200, null=True)),
                ('base_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
